version: "3.9"
services:
  server:
    build:  ./backend
    ports: 
    - "8000:8000"
    volumes: 
    - ./backend:/app
    environment: 
      FASTAPI_ENV: development
  web:
    build: ./frontend 
    ports: 
      - "4200:4200"
    volumes: 
      - ./frontend:/user/src/app
    depends_on: 
      - server

